services:
  course:
    container_name: docker_course_bot
    image: docker_course_image
    build: ./app
      # context: .
    env_file:
      - ./app/.env
    # environment:
    #   BOT_TOKEN: "${BOT_TOKEN}"
    depends_on:
      - db

  db:
    container_name: docker_course_psql
    image: postgres:15.3
    volumes:
      - ./dbdata/postgres:/data/postgres
    ports:
      - "5431:5432"
    env_file:
      - ./app/.env
    environment:
      PGDATA: /data/postgres


  pgadmin:
      container_name: docker_course_pgadmin
      image: dpage/pgadmin4
      profiles:
        - "dev"
      restart: on-failure
      env_file:
        - ./app/.env
      ports:
        - "5050:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: 
